### ISSUE TITLE
5.0: submission validation messages aren't very visible

### ISSUE THREAD

**Issue by ericras** [unl/UNL_ENews#70]
they appear at the top of the screen and aren't noticeable.  and they push down the thumbnail widget. they need to float again

**Comment by ericras** [comment]
"overlay" class on the notice

**Comment by ericras** [comment]
is it in 5.0?

The deprecated works: "wdn_notice negate overlay"

**Comment by ericras** [comment]
and that overlay for the notice doesn’t totally help.  Since the validation that triggers it is JS (the page is not reloaded) the notice is off the screen at the top.  That’s an issue too with the current site in 4.1

**Comment by jsturek** [comment]
Fixed with: https://github.com/unl/UNL_ENews/commit/ce882fd8c0a66922d0f1c35e5cd48e0e1117c138
